FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# api.wechalet

Rest API for wechalet a cabin rental agency in Austin, Quebec, Canada.


##  get rules [/api/rules]
### api/rules [GET]
+ Request (application/json)

        {
            "api_token": ""
        }
+ Response 200 (application/json)

    + Body

            {
                  "data": [
                    {
                      "id": "a5fadf08-df0d-4815-ad56-492878044906",
                      "rule": "Children are welcome (2 to 12 years old)"
                    },
                    {
                      "id": "6b8a7915-0ccf-4803-8899-856ab86d8fed",
                      "rule": "Pets are welcome"
                    },
                    {
                      "id": "86ba3b54-cdd9-4d1d-8254-c98b9aa13675",
                      "rule": "Smoking inside is allowed"
                    },
                    {
                      "id": "d641b86e-403c-4daa-a76d-8ee96ff756db",
                      "rule": "Parties and events are allowed"
                    }
                  ]
                }
                
+ Response 400 (application/json)

    + Body

             {
                  "message": "Unauthenticated."
             }


## property rules [/api/properties/{uuid}/rules]
+ Parameters

    + uuid (required, string) ... ID of the Property

### api/properties/{uuid}/rules [GET]
+ Request (application/json)

        {
            "api_token": ""
        }

+ Response 200 (application/json)

    
    + Body

            {
              "data": [
                "children_are_welcome_2_to_12_years_old": false,
                "infants_under_2_years_old_are_welcome": false,
                "pets_are_welcome": true,
                "smoking_inside_is_allowed": true,
                "parties_and_events_are_allowed": true
              ]
            }
            


+ Response 400 (application/json)

    + Body

             {
                  "message": "Unauthenticated."
             }
                

+ Response 404 (application/json)

    + Body

             {
                    "errors": "Resource not found!"
             }
### api/properties/{uuid}/rules [PUT]
+ Request (application/json)

            {
                "api_token": "",
                "rules": {
                        "children_are_welcome_2_to_12_years_old" : true,
                        "infants_under_2_years_old_are_welcome": true,
                        "pets_are_welcome" : false,
                        "smoking_inside_is_allowed" : false,
                        "parties_and_events_are_allowed" : false
                        }
            }


+ Response 200 (application/json)

    
    + Body

            {
              "data": {
                          "children_are_welcome_2_to_12_years_old": true,
                            "infants_under_2_years_old_are_welcome": true,
                            "pets_are_welcome": false,
                            "smoking_inside_is_allowed": false,
                            "parties_and_events_are_allowed": false
                      }
            }

+ Response 400 (application/json)

    + Body

             {
                  "message": "Unauthenticated."
             }
                

+ Response 404 (application/json)

    + Body

             {
                    "errors": "Resource not found!"
             }
             
+ Response 422 (application/json)

    + Body

             {
                    "message": "The given data was invalid.",
                      "errors": {
                        "rules": [
                          "The rules field is required."
                        ],
                        "rules.children_are_welcome_2_to_12_years_old": [
                          "The rules.children are welcome 2 to 12 years old field is required."
                        ],
                        "rules.infants_under_2_years_old_are_welcome": [
                          "The rules.infants under 2 years old are welcome field is required."
                        ],
                        "rules.pets_are_welcome": [
                          "The rules.pets are welcome field is required."
                        ],
                        "rules.smoking_inside_is_allowed": [
                          "The rules.smoking inside is allowed field is required."
                        ],
                        "rules.parties_and_events_are_allowed": [
                          "The rules.parties and events are allowed field is required."
                        ]
                      }
             }
             
## get amenities  [/api/amenities]
### api/amenities [GET]
+ Request (application/json)

        {
            "api_token": ""
        }

+ Response 200 (application/json)

        {
              "data": [
               {
                      "id": "5afcd6c1-92db-47ef-89dc-67fe87b6cdae",
                      "name": "Air conditioning",
                      "slug": "air_conditioning",
                      "group": "general"
                    },
                    {
                      "id": "8662940e-587b-4659-ad09-983cac77a22f",
                      "name": "Bed linens",
                      "slug": "bed_linens",
                      "group": "general"
                    },
                    {
                      "id": "74768c2f-dbc6-4d50-943c-9440f1e53d7c",
                      "name": "Cable TV",
                      "slug": "cable_tv",
                      "group": "general"
                    },
                    {
                      "id": "ecc54c30-d46d-4c73-9e01-84f152ee7bf3",
                      "name": "Dryer",
                      "slug": "dryer",
                      "group": "general"
                    },
                    {
                      "id": "5f2ad8b0-0ca4-4d3e-964e-f1f90eb32344",
                      "name": "DVD \/ Blue Ray",
                      "slug": "dvd_blue_ray",
                      "group": "general"
                    },
                    {
                      "id": "be34f982-2b71-4403-872b-b8b4feafde6f",
                      "name": "Extra pillows and blankets",
                      "slug": "extra_pillows_and_blankets",
                      "group": "general"
                    },
                    {
                      "id": "6b1be73f-d551-41cb-be48-19dfba459309",
                      "name": "Firewood included",
                      "slug": "firewood_included",
                      "group": "general"
                    },
                    {
                      "id": "3820c6d1-8054-4808-b1cd-e2414b846ff3",
                      "name": "Hair dryer",
                      "slug": "hair_dryer",
                      "group": "general"
                    },
                    {
                      "id": "53838e65-48b0-456f-aead-aae61ac88cce",
                      "name": "Hangers in closets",
                      "slug": "hangers_in_closets",
                      "group": "general"
                    },
                    {
                      "id": "ffa8889b-e269-47f8-bf7e-12533c949090",
                      "name": "Heated floors",
                      "slug": "heated_floors",
                      "group": "general"
                    },
                    {
                      "id": "fc831efc-85f8-455b-b800-2bd033d29122",
                      "name": "Heating",
                      "slug": "heating",
                      "group": "general"
                    },
                    {
                      "id": "084ca42b-1473-41de-9da7-5aba6c162045",
                      "name": "Home essentials",
                      "slug": "home_essentials",
                      "group": "general"
                    },
                    {
                      "id": "106782d9-2911-4050-9d3b-b1f7ca7dd254",
                      "name": "Hot water",
                      "slug": "hot_water",
                      "group": "general"
                    },
                    {
                      "id": "ad75f152-9b01-4fd6-8331-46a8f300523b",
                      "name": "Indoor fireplace",
                      "slug": "indoor_fireplace",
                      "group": "general"
                    },
                    {
                      "id": "f279c089-be9d-492e-80a3-e254c5db7450",
                      "name": "Iron",
                      "slug": "iron",
                      "group": "general"
                    },
                    {
                      "id": "558a57e2-5cad-49f5-b554-f70cc6fd2353",
                      "name": "Kitchen",
                      "slug": "kitchen",
                      "group": "general"
                    },
                    {
                      "id": "2268f5bc-5a27-4a80-8c74-67957c7c0b40",
                      "name": "Laptop friendly workspace",
                      "slug": "laptop_friendly_workspace",
                      "group": "general"
                    },
                    {
                      "id": "66847f70-e9cb-4d5d-a78c-74797c5ee60b",
                      "name": "Potable water",
                      "slug": "potable_water",
                      "group": "general"
                    },
                    {
                      "id": "06248074-b020-434c-864a-e1246b5a9b32",
                      "name": "Shampoo & soap",
                      "slug": "shampoo_soap",
                      "group": "general"
                    },
                    {
                      "id": "b8bf4a0c-f63e-488d-a957-58297de2b473",
                      "name": "Toilet paper",
                      "slug": "toilet_paper",
                      "group": "general"
                    },
                    {
                      "id": "ded2a36d-1190-4e52-81cc-b1efede54eac",
                      "name": "Towels",
                      "slug": "towels",
                      "group": "general"
                    },
                    {
                      "id": "c64e03ea-6700-4322-80c3-bb529cc4932c",
                      "name": "TV",
                      "slug": "tv",
                      "group": "general"
                    },
                    {
                      "id": "aaafd785-8732-4319-a08b-055f5e662532",
                      "name": "Washer",
                      "slug": "washer",
                      "group": "general"
                    },
                    {
                      "id": "d27fffb0-f6a1-42c4-970c-795b1f0c831f",
                      "name": "Wireless Internet",
                      "slug": "wireless_internet",
                      "group": "general"
                    },
                    {
                      "id": "8d95fdc0-ab5f-4495-bb8a-8e4f7c162505",
                      "name": "Baby bath",
                      "slug": "baby_bath",
                      "group": "family features"
                    },
                    {
                      "id": "ad8f2aad-d1b6-46bc-819e-d1108783b2e0",
                      "name": "Baby monitor",
                      "slug": "baby_monitor",
                      "group": "family features"
                    },
                    {
                      "id": "04fd985b-4c60-4123-9498-80e6348c6eab",
                      "name": "Babysitter referrals",
                      "slug": "babysitter_referrals",
                      "group": "family features"
                    },
                    {
                      "id": "22111293-0148-4e2a-ac04-0d64a0c9fba5",
                      "name": "Changing tableBathtub",
                      "slug": "changing_tablebathtub",
                      "group": "family features"
                    },
                    {
                      "id": "122a52bd-00e4-4af3-9af3-202445114037",
                      "name": "Children’s books and toys",
                      "slug": "childrens_books_and_toys",
                      "group": "family features"
                    },
                    {
                      "id": "b69eb3f5-3491-42c8-b5dc-e90a85b2d867",
                      "name": "Children’s dinnerware",
                      "slug": "childrens_dinnerware",
                      "group": "family features"
                    },
                    {
                      "id": "da9ffa06-db29-43b1-8cca-2001df4bc2cc",
                      "name": "Crib",
                      "slug": "crib",
                      "group": "family features"
                    },
                    {
                      "id": "40886ef7-fa78-4dae-af6f-e926d09d1cf3",
                      "name": "Fireplace guards",
                      "slug": "fireplace_guards",
                      "group": "family features"
                    },
                    {
                      "id": "15fac940-99b9-4c89-aa99-4d92729021ec",
                      "name": "Foosball table",
                      "slug": "foosball_table",
                      "group": "family features"
                    },
                    {
                      "id": "356cf0a9-dc6c-46e1-aa27-de3951a438f3",
                      "name": "Game console",
                      "slug": "game_console",
                      "group": "family features"
                    },
                    {
                      "id": "cb530de7-d1b0-4362-b00f-a3192b2f06ec",
                      "name": "High chair",
                      "slug": "high_chair",
                      "group": "family features"
                    },
                    {
                      "id": "9a210ed7-ab2f-4f26-b74d-c1b1e67d977e",
                      "name": "Outlet covers",
                      "slug": "outlet_covers",
                      "group": "family features"
                    },
                    {
                      "id": "d8d78dcc-359b-41e5-bb90-b3257831aff0",
                      "name": "Pack ’n Play\/travel crib",
                      "slug": "pack_n_playtravel_crib",
                      "group": "family features"
                    },
                    {
                      "id": "645807b2-fec2-4eb6-817d-00f56ef6fc31",
                      "name": "Ping pong table",
                      "slug": "ping_pong_table",
                      "group": "family features"
                    },
                    {
                      "id": "2709f5fe-82da-402e-9f68-a91d84d1b9ae",
                      "name": "Pool table",
                      "slug": "pool_table",
                      "group": "family features"
                    },
                    {
                      "id": "0f6fd9ab-d0f3-455f-a007-6167c5005b5d",
                      "name": "Room-darkening shades",
                      "slug": "room_darkening_shades",
                      "group": "family features"
                    },
                    {
                      "id": "7c8e65ff-3319-44f1-a58c-f81378fe288a",
                      "name": "Stair gates",
                      "slug": "stair_gates",
                      "group": "family features"
                    },
                    {
                      "id": "f4eed9dd-8328-42e6-b064-2cd8e9701a13",
                      "name": "Table corner guards",
                      "slug": "table_corner_guards",
                      "group": "family features"
                    },
                    {
                      "id": "f06ffb79-f987-4266-af84-a1caf66ff0cc",
                      "name": "Window guards",
                      "slug": "window_guards",
                      "group": "family features"
                    },
                    {
                      "id": "2379ad45-a8b0-43f8-be2a-1e8c7ecac810",
                      "name": "Coffee maker",
                      "slug": "coffee_maker",
                      "group": "kitchen"
                    },
                    {
                      "id": "27dbee79-579d-4ed9-ad8e-1238f133b247",
                      "name": "Cooking basics",
                      "slug": "cooking_basics",
                      "group": "kitchen"
                    },
                    {
                      "id": "44f9f1ef-97eb-473c-8e69-e868a0c666e8",
                      "name": "Dishes and silverware",
                      "slug": "dishes_and_silverware",
                      "group": "kitchen"
                    },
                    {
                      "id": "9a21a8cf-f334-4656-9f0f-002642d6661a",
                      "name": "Dishwasher",
                      "slug": "dishwasher",
                      "group": "kitchen"
                    },
                    {
                      "id": "b48b67c2-30bc-48e2-a059-c0f610259c63",
                      "name": "Microwave",
                      "slug": "microwave",
                      "group": "kitchen"
                    },
                    {
                      "id": "8f2335ad-1298-423f-9990-eb5343032067",
                      "name": "Oven",
                      "slug": "oven",
                      "group": "kitchen"
                    },
                    {
                      "id": "725f1fd4-6ad9-4540-9d76-8fdbe17a2016",
                      "name": "Pots and pans",
                      "slug": "pots_and_pans",
                      "group": "kitchen"
                    },
                    {
                      "id": "7a1b04a9-999d-469f-b0e5-1f9a629917bb",
                      "name": "Refrigerator",
                      "slug": "refrigerator",
                      "group": "kitchen"
                    },
                    {
                      "id": "90b2b717-da40-4598-8e75-d36fa1d649d0",
                      "name": "Stove",
                      "slug": "stove",
                      "group": "kitchen"
                    },
                    {
                      "id": "463dc946-4c8c-4271-8f8f-717e80168302",
                      "name": "Access to water",
                      "slug": "access_to_water",
                      "group": "outdoor"
                    },
                    {
                      "id": "4fc180e4-de04-473e-953a-39a0aa4a79b7",
                      "name": "BBQ \/ Grill",
                      "slug": "bbq_grill",
                      "group": "outdoor"
                    },
                    {
                      "id": "288212d6-4e3c-4a32-ac6b-0717592bf335",
                      "name": "Beach chairs",
                      "slug": "beach_chairs",
                      "group": "outdoor"
                    },
                    {
                      "id": "f0168bc9-a17a-4e44-b9e2-f05f5abb3154",
                      "name": "Beachfront",
                      "slug": "beachfront",
                      "group": "outdoor"
                    },
                    {
                      "id": "2e5bf146-1cd1-4b4d-bde6-16620beb12dd",
                      "name": "By a river",
                      "slug": "by_a_river",
                      "group": "outdoor"
                    },
                    {
                      "id": "3e734f17-8480-4bf8-82b2-dbce3bfbb955",
                      "name": "Dock",
                      "slug": "dock",
                      "group": "outdoor"
                    },
                    {
                      "id": "31e0daaa-9820-4b79-a1e8-786d015ed016",
                      "name": "Fire pit",
                      "slug": "fire_pit",
                      "group": "outdoor"
                    },
                    {
                      "id": "2c121a1c-e983-47c1-87ff-e3c08325fdf8",
                      "name": "Garden or backyard",
                      "slug": "garden_or_backyard",
                      "group": "outdoor"
                    },
                    {
                      "id": "2ab27b0a-ae23-45be-9fa2-39e143ad7e19",
                      "name": "Hamak",
                      "slug": "hamak",
                      "group": "outdoor"
                    },
                    {
                      "id": "55d7f516-7d0c-45ea-84a4-70e51e514a1f",
                      "name": "Hot tub \/ Spa",
                      "slug": "hot_tub_spa",
                      "group": "outdoor"
                    },
                    {
                      "id": "77c4e005-67e0-4017-a440-97ec82fad564",
                      "name": "Lakefront",
                      "slug": "lakefront",
                      "group": "outdoor"
                    },
                    {
                      "id": "56013cbd-e3da-4375-b524-78a09079a551",
                      "name": "Life jackets",
                      "slug": "life_jackets",
                      "group": "outdoor"
                    },
                    {
                      "id": "5baae93a-a69b-4409-9d6a-6115a7a1e284",
                      "name": "Patio furniture",
                      "slug": "patio_furniture",
                      "group": "outdoor"
                    },
                    {
                      "id": "6dfff6fc-6e3c-4a80-bd97-2359844de7c0",
                      "name": "Patio or balcony",
                      "slug": "patio_or_balcony",
                      "group": "outdoor"
                    },
                    {
                      "id": "232baff9-baef-463c-ac09-902baa7e559e",
                      "name": "Pool",
                      "slug": "pool",
                      "group": "outdoor"
                    },
                    {
                      "id": "5106f5c4-e482-4745-b481-40bc12915b39",
                      "name": "Sandy beach",
                      "slug": "sandy_beach",
                      "group": "outdoor"
                    },
                    {
                      "id": "6e7d84ab-545b-4278-8ce6-e9b6d2afba94",
                      "name": "Sauna",
                      "slug": "sauna",
                      "group": "outdoor"
                    },
                    {
                      "id": "12c585e3-6959-4bde-900e-6176e0d96df4",
                      "name": "Ski in \/ ski out",
                      "slug": "ski_in_ski_out",
                      "group": "outdoor"
                    },
                    {
                      "id": "eff43870-fa96-472b-94e8-846c36ac2db0",
                      "name": "Volleyball net",
                      "slug": "volleyball_net",
                      "group": "outdoor"
                    },
                    {
                      "id": "2eedc3d5-51a1-49e6-a659-7d8bca265ef3",
                      "name": "Alpine Skiing",
                      "slug": "alpine_skiing",
                      "group": "sports & adventures nearby"
                    },
                    {
                      "id": "d3a81cba-fc19-4e38-952f-2d372a93f301",
                      "name": "ATV trail",
                      "slug": "atv_trail",
                      "group": "sports & adventures nearby"
                    },
                    {
                      "id": "05f154e4-2b30-415b-8755-629ff4a3d6f9",
                      "name": "Basketball",
                      "slug": "basketball",
                      "group": "sports & adventures nearby"
                    },
                    {
                      "id": "29b3abec-d325-4dbd-bbea-65b15cae6619",
                      "name": "Boating",
                      "slug": "boating",
                      "group": "sports & adventures nearby"
                    },
                    {
                      "id": "ce6639c1-90f0-4fdc-916d-6a8d1152b016",
                      "name": "Parasailing",
                      "slug": "parasailing",
                      "group": "sports & adventures nearby"
                    },
                    {
                      "id": "7a9ec0b4-3382-403b-989b-6220ed330157",
                      "name": "Road biking",
                      "slug": "road_biking",
                      "group": "sports & adventures nearby"
                    },
                    {
                      "id": "a315fe7d-39ff-4ea7-bb5f-cbd4ab859d09",
                      "name": "Mountain Biking",
                      "slug": "mountain_biking",
                      "group": "sports & adventures nearby"
                    },
                    {
                      "id": "9e3aa8a7-faaa-49aa-933d-6e302632d55b",
                      "name": "Kayaking",
                      "slug": "kayaking",
                      "group": "sports & adventures nearby"
                    },
                    {
                      "id": "9eb15b3c-5c7b-470b-9d92-e153478e9a1a",
                      "name": "Jet skiing",
                      "slug": "jet_skiing",
                      "group": "sports & adventures nearby"
                    },
                    {
                      "id": "888cf70b-2ffd-4c4d-aec7-5d323e62746e",
                      "name": "Ice Climbing",
                      "slug": "ice_climbing",
                      "group": "sports & adventures nearby"
                    },
                    {
                      "id": "5d0e54fc-e7da-4e6e-8859-c1f64e7ba491",
                      "name": "Horseback riding",
                      "slug": "horseback_riding",
                      "group": "sports & adventures nearby"
                    },
                    {
                      "id": "392c88bc-bb90-4032-992d-3e0bd51cb1f6",
                      "name": "Hockey",
                      "slug": "hockey",
                      "group": "sports & adventures nearby"
                    },
                    {
                      "id": "d132eb4a-3fcf-4ccb-8f45-34e6538f6202",
                      "name": "Hiking",
                      "slug": "hiking",
                      "group": "sports & adventures nearby"
                    },
                    {
                      "id": "c57fb3c8-783b-41c9-992e-4f8cc55c0e92",
                      "name": "Golf",
                      "slug": "golf",
                      "group": "sports & adventures nearby"
                    },
                    {
                      "id": "d19c9dfc-d8be-42cc-9734-ffac75e31813",
                      "name": "Fishing",
                      "slug": "fishing",
                      "group": "sports & adventures nearby"
                    },
                    {
                      "id": "87a25991-dce5-43b6-b63b-430435e6877a",
                      "name": "Deepsea fishing",
                      "slug": "deepsea_fishing",
                      "group": "sports & adventures nearby"
                    },
                    {
                      "id": "9e053dea-9f77-44ab-88ad-423a390dcb47",
                      "name": "Cross-country skiing",
                      "slug": "cross_country_skiing",
                      "group": "sports & adventures nearby"
                    },
                    {
                      "id": "e8b05015-57f4-42d3-9f1d-60e4090af93f",
                      "name": "Caving",
                      "slug": "caving",
                      "group": "sports & adventures nearby"
                    },
                    {
                      "id": "7e4a4521-6895-4eac-a8be-4c46df32ee8f",
                      "name": "Canoeing",
                      "slug": "canoeing",
                      "group": "sports & adventures nearby"
                    },
                    {
                      "id": "4aa23158-2962-4d34-bfd4-7d70f0fa2aea",
                      "name": "Rock Climbing",
                      "slug": "rock_climbing",
                      "group": "sports & adventures nearby"
                    },
                    {
                      "id": "d3aeda4e-2e76-4d35-b53b-c2c2ded9eec9",
                      "name": "Rollerblading",
                      "slug": "rollerblading",
                      "group": "sports & adventures nearby"
                    },
                    {
                      "id": "96d417d8-a5fb-4a67-b0c7-4b0ba924d7ed",
                      "name": "Running",
                      "slug": "running",
                      "group": "sports & adventures nearby"
                    },
                    {
                      "id": "ea128561-9d41-49f0-8b0a-a482955cdbca",
                      "name": "Sailing",
                      "slug": "sailing",
                      "group": "sports & adventures nearby"
                    },
                    {
                      "id": "162a9529-642f-4d13-bb0c-31d3cb4369a5",
                      "name": "Scuba diving",
                      "slug": "scuba_diving",
                      "group": "sports & adventures nearby"
                    },
                    {
                      "id": "76b4f1af-3cf5-485c-bd11-c2b279140780",
                      "name": "Skating",
                      "slug": "skating",
                      "group": "sports & adventures nearby"
                    },
                    {
                      "id": "7dc997b3-4e0e-41ac-9ab8-a271ba95091e",
                      "name": "Skydiving",
                      "slug": "skydiving",
                      "group": "sports & adventures nearby"
                    },
                    {
                      "id": "4a3ffc24-a555-408a-a0b0-8a773fc4550a",
                      "name": "Snorkeling",
                      "slug": "snorkeling",
                      "group": "sports & adventures nearby"
                    },
                    {
                      "id": "a4700bd2-97aa-4084-a6e4-721ced617e23",
                      "name": "Snowboarding",
                      "slug": "snowboarding",
                      "group": "sports & adventures nearby"
                    },
                    {
                      "id": "191d4190-5eaa-4c45-8f41-2e2f9ea65159",
                      "name": "Snowmobile trail",
                      "slug": "snowmobile_trail",
                      "group": "sports & adventures nearby"
                    },
                    {
                      "id": "e64bc386-36e8-4280-a653-0b5afd74847e",
                      "name": "Snowshoeing",
                      "slug": "snowshoeing",
                      "group": "sports & adventures nearby"
                    },
                    {
                      "id": "e35eb066-b962-4502-ac7b-9bada241ba03",
                      "name": "Swimming",
                      "slug": "swimming",
                      "group": "sports & adventures nearby"
                    },
                    {
                      "id": "44c7e034-c2de-474e-a23c-a2fb4b2b228d",
                      "name": "Windsurfing",
                      "slug": "windsurfing",
                      "group": "sports & adventures nearby"
                    },
                    {
                      "id": "a4d77fb6-fc9e-4ddf-aabc-3aaf65898b3c",
                      "name": "Tennis",
                      "slug": "tennis",
                      "group": "sports & adventures nearby"
                    },
                    {
                      "id": "eefd0343-49bb-4681-a262-68c4384929d5",
                      "name": "Tree Climbing",
                      "slug": "tree_climbing",
                      "group": "sports & adventures nearby"
                    },
                    {
                      "id": "f48c5de2-9f6a-4a38-b874-f8db4640ed37",
                      "name": "Volleyball",
                      "slug": "volleyball",
                      "group": "sports & adventures nearby"
                    },
                    {
                      "id": "e196f437-b848-4d7f-85cf-8d6b0a525830",
                      "name": "Water skiing",
                      "slug": "water_skiing",
                      "group": "sports & adventures nearby"
                    },
                    {
                      "id": "5c953bb0-675a-4cf6-b629-a37ce6b1e44e",
                      "name": "Water sliding",
                      "slug": "water_sliding",
                      "group": "sports & adventures nearby"
                    },
                    {
                      "id": "2b751be9-3051-4a92-ae22-d5065c82a953",
                      "name": "Whitewater rafting",
                      "slug": "whitewater_rafting",
                      "group": "sports & adventures nearby"
                    },
                    {
                      "id": "ca15dc07-d360-4905-a671-12896f868632",
                      "name": "Elevator in the building",
                      "slug": "elevator_in_the_building",
                      "group": "accessibility"
                    },
                    {
                      "id": "620bc931-9feb-41f2-85d8-7eff13e147fe",
                      "name": "Private entrance",
                      "slug": "private_entrance",
                      "group": "accessibility"
                    },
                    {
                      "id": "9149e92b-6480-482e-a071-1b57de4bc39d",
                      "name": "Single level home",
                      "slug": "single_level_home",
                      "group": "accessibility"
                    },
                    {
                      "id": "ddd88a8c-09e8-4364-9556-80602c6dfd8f",
                      "name": "Wheelchair accessible",
                      "slug": "wheelchair_accessible",
                      "group": "accessibility"
                    },
                    {
                      "id": "ce4e9511-6a18-40ad-bf62-2042a87c197d",
                      "name": "Breakfast included",
                      "slug": "breakfast_included",
                      "group": "services"
                    },
                    {
                      "id": "f9a49e78-46d6-41fd-bca9-1a6a5a6868b4",
                      "name": "EV charger",
                      "slug": "ev_charger",
                      "group": "services"
                    },
                    {
                      "id": "3e3d9b34-e91c-420f-a2aa-b3a349037fab",
                      "name": "Free gym \/ Fitness centre",
                      "slug": "free_gym_fitness_centre",
                      "group": "services"
                    },
                    {
                      "id": "7c2f5f05-2fb5-44a7-a8a0-e315df061dc4",
                      "name": "Free parking on premises",
                      "slug": "free_parking_on_premises",
                      "group": "services"
                    },
                    {
                      "id": "62bc702c-2586-4b6a-8007-39306d3ec95e",
                      "name": "Guided tours",
                      "slug": "guided_tours",
                      "group": "services"
                    },
                    {
                      "id": "5dd54af9-d493-4816-afe6-3543d23727b3",
                      "name": "Maid service included",
                      "slug": "maid_service_included",
                      "group": "services"
                    },
                    {
                      "id": "f2f9a3ad-0165-489c-8ae1-34d6ca959165",
                      "name": "Restaurant on site",
                      "slug": "restaurant_on_site",
                      "group": "services"
                    },
                    {
                      "id": "b65df0fd-a484-4c6c-b2ac-58708b2abe4d",
                      "name": "Spa services",
                      "slug": "spa_services",
                      "group": "services"
                    },
                    {
                      "id": "b88fef14-88bb-45e6-bdae-9304b85291db",
                      "name": "Tea & coffee included",
                      "slug": "tea_coffee_included",
                      "group": "services"
                    },
                    {
                      "id": "2f9f8c94-0247-47be-8c27-baf7ba2c94ee",
                      "name": "Art show",
                      "slug": "art_show",
                      "group": "suitable for events"
                    },
                    {
                      "id": "9017c80e-2263-4061-b939-cf117ac7eeae",
                      "name": "Bachelor(ette) party",
                      "slug": "bachelorette_party",
                      "group": "suitable for events"
                    },
                    {
                      "id": "5b8cb72d-7768-4bc2-bf5d-b3dfc3fa9304",
                      "name": "Birthday party",
                      "slug": "birthday_party",
                      "group": "suitable for events"
                    },
                    {
                      "id": "689d1de3-e688-4e72-be8e-3f28e7a360ef",
                      "name": "Conference",
                      "slug": "conference",
                      "group": "suitable for events"
                    },
                    {
                      "id": "f45b4b36-548c-4dec-9547-df80d945cea3",
                      "name": "Corporate meeting",
                      "slug": "corporate_meeting",
                      "group": "suitable for events"
                    },
                    {
                      "id": "3601de78-1db6-4e4d-b583-1c8ae5603da7",
                      "name": "Executive retreat",
                      "slug": "executive_retreat",
                      "group": "suitable for events"
                    },
                    {
                      "id": "f0801fbe-92fd-4295-971c-a77127a4d2c7",
                      "name": "Friends & Family meeting",
                      "slug": "friends_family_meeting",
                      "group": "suitable for events"
                    },
                    {
                      "id": "d30def26-1089-450f-81e6-298240789859",
                      "name": "Photo & Film Shoot",
                      "slug": "photo_film_shoot",
                      "group": "suitable for events"
                    },
                    {
                      "id": "7e0c7c67-8341-4ffa-af88-4252993732f7",
                      "name": "Product launch",
                      "slug": "product_launch",
                      "group": "suitable for events"
                    },
                    {
                      "id": "f29fb86a-4438-43a1-ba77-e11b4db8039e",
                      "name": "Seminar & Networking",
                      "slug": "seminar_networking",
                      "group": "suitable for events"
                    },
                    {
                      "id": "34be44f1-2743-497b-aa06-731cd22f2bb4",
                      "name": "Sport team training",
                      "slug": "sport_team_training",
                      "group": "suitable for events"
                    },
                    {
                      "id": "fd49b63d-5a04-44de-aecf-35bb166c0af9",
                      "name": "Wedding",
                      "slug": "wedding",
                      "group": "suitable for events"
                    }
                  ]
            }       
  
+ Response 400 (application/json)

    + Body

             {
                  "message": "Unauthenticated."
             }
                

+ Response 404 (application/json)

    + Body

             {
                    "errors": "Resource not found!"
             }
             
             

## get property amenities [/api/properties/{uuid}/amenities]
+ Parameters

    + uuid (required, string) ... ID of the Property

### api/properties/{uuid}/amenities [GET]
+ Request (application/json)

        {
            "api_token": ""
        }

+ Response 200 (application/json)

    
    + Body

            {
               "data": {
                            "access_to_water": false,
                            "air_conditioning": false,
                            "pets_are_welcome": false,
                            "alpine_skiing": false,
                            "art_show": false,
                            "atv_trail": false,
                            "baby_bath": false,
                            "baby_monitor": false,
                            "babysitter_referrals": false,
                            "bachelorette_party": false,
                            "basketball": false,
                            "bbq_grill": false,
                            "beach_chairs": false,
                            "beachfront": false,
                            "bed_linens": false,
                            "birthday_party": false,
                            "boating": false,
                            "breakfast_included": false,
                            "by_a_river": false,
                            "cable_tv": false,
                            "canoeing": false,
                            "changing_tablebathtub": false,
                            "caving": false,
                            "cooking_basics": false,
                            "corporate_meeting": false,
                            "conference": false,
                            "coffee_maker": false,
                            "childrens_dinnerware": false,
                            "childrens_books_and_toys": false,
                            "crib": false,
                            "cross_country_skiing": false,
                            "deepsea_fishing": false,
                            "dishes_and_silverware": false,
                            "dishwasher": false,
                            "dock": false,
                            "dryer": false,
                            "dvd_blue_ray": false,
                            "ev_charger": false,
                            "executive_retreat": false,
                            "extra_pillows_and_blankets": false,
                            "fire_pit": false,
                            "fireplace_guards": false,
                            "firewood_included": false,
                            "free_gym_fitness_centre": false,
                            "free_parking_on_premises": false,
                            "friends_family_meeting": false,
                            "game_console": false,
                            "garden_or_backyard": false,
                            "golf": false,
                            "guided_tours": false,
                            "hair_dryer": false,
                            "hamak": false,
                            "hangers_in_closets": false,
                            "heated_floors": false,
                            "heating": false,
                            "high_chair": false,
                            "hiking": false,
                            "hockey": false,
                            "home_essentials": false,
                            "horseback_riding": false,
                            "foosball_table": false,
                            "fishing": false,
                            "hot_tub_spa": false,
                            "hot_water": false,
                            "ice_climbing": false,
                            "indoor_fireplace": false,
                            "iron": false,
                            "jet_skiing": false,
                            "kayaking": false,
                            "kitchen": false,
                            "lakefront": false,
                            "laptop_friendly_workspace": false,
                            "life_jackets": false,
                            "maid_service_included": false,
                            "microwave": false,
                            "mountain_biking": false,
                            "outlet_covers": false,
                            "oven": false,
                            "pack_n_playtravel_crib": false,
                            "parasailing": false,
                            "patio_furniture": false,
                            "patio_or_balcony": false,
                            "photo_film_shoot": false,
                            "ping_pong_table": false,
                            "pool": false,
                            "pool_table": false,
                            "pots_and_pans": false,
                            "private_entrance": false,
                            "product_launch": false,
                            "refrigerator": false,
                            "road_biking": false,
                            "rock_climbing": false,
                            "rollerblading": false,
                            "room_darkening_shades": false,
                            "running": false,
                            "sailing": false,
                            "sandy_beach": false,
                            "sauna": false,
                            "scuba_diving": false,
                            "shampoo_soap": false,
                            "single_level_home": false,
                            "skating": false,
                            "ski_in_ski_out": false,
                            "skydiving": false,
                            "snorkeling": false,
                            "snowboarding": false,
                            "snowmobile_trail": false,
                            "snowshoeing": false,
                            "spa_services": false,
                            "sport_team_training": false,
                            "stair_gates": false,
                            "stove": false,
                            "swimming": false,
                            "table_corner_guards": false,
                            "tea_coffee_included": false,
                            "tennis": false,
                            "toilet_paper": false,
                            "towels": false,
                            "tree_climbing": false,
                            "tv": false,
                            "volleyball": false,
                            "volleyball_net": false,
                            "washer": false,
                            "water_skiing": false,
                            "water_sliding": false,
                            "wedding": false,
                            "wheelchair_accessible": false,
                            "whitewater_rafting": false,
                            "window_guards": false,
                            "windsurfing": false,
                            "wireless_internet": false
                          }
            }
            


+ Response 400 (application/json)

    + Body

             {
                  "message": "Unauthenticated."
             }
                

+ Response 404 (application/json)

    + Body

             {
                    "errors": "Resource not found!"
             }
### api/properties/{uuid}/amenities [PUT]
+ Request (application/json)

        {
            "api_token": "",
            "amenities" :
                            {
                            "access_to_water": true,
                            "air_conditioning": true,
                            "pets_are_welcome": false,
                            "alpine_skiing": false,
                            "art_show": false,
                            "atv_trail": false,
                            "baby_bath": false,
                            "baby_monitor": false,
                            "babysitter_referrals": false,
                            "bachelorette_party": false,
                            "basketball": false,
                            "bbq_grill": false,
                            "beach_chairs": false,
                            "beachfront": false,
                            "bed_linens": false,
                            "birthday_party": false,
                            "boating": false,
                            "breakfast_included": false,
                            "by_a_river": false,
                            "cable_tv": false,
                            "canoeing": false,
                            "changing_tablebathtub": false,
                            "caving": false,
                            "cooking_basics": false,
                            "corporate_meeting": false,
                            "conference": false,
                            "coffee_maker": false,
                            "childrens_dinnerware": false,
                            "childrens_books_and_toys": false,
                            "crib": false,
                            "cross_country_skiing": false,
                            "deepsea_fishing": false,
                            "dishes_and_silverware": false,
                            "dishwasher": false,
                            "dock": false,
                            "dryer": false,
                            "dvd_blue_ray": false,
                            "ev_charger": false,
                            "executive_retreat": false,
                            "extra_pillows_and_blankets": false,
                            "fire_pit": false,
                            "fireplace_guards": false,
                            "firewood_included": false,
                            "free_gym_fitness_centre": false,
                            "free_parking_on_premises": false,
                            "friends_family_meeting": false,
                            "game_console": false,
                            "garden_or_backyard": false,
                            "golf": false,
                            "guided_tours": false,
                            "hair_dryer": false,
                            "hamak": false,
                            "hangers_in_closets": false,
                            "heated_floors": false,
                            "heating": false,
                            "high_chair": false,
                            "hiking": false,
                            "hockey": false,
                            "home_essentials": false,
                            "horseback_riding": false,
                            "foosball_table": false,
                            "fishing": false,
                            "hot_tub_spa": false,
                            "hot_water": false,
                            "ice_climbing": false,
                            "indoor_fireplace": false,
                            "iron": false,
                            "jet_skiing": false,
                            "kayaking": false,
                            "kitchen": false,
                            "lakefront": false,
                            "laptop_friendly_workspace": false,
                            "life_jackets": false,
                            "maid_service_included": false,
                            "microwave": false,
                            "mountain_biking": false,
                            "outlet_covers": false,
                            "oven": false,
                            "pack_n_playtravel_crib": false,
                            "parasailing": false,
                            "patio_furniture": false,
                            "patio_or_balcony": false,
                            "photo_film_shoot": false,
                            "ping_pong_table": false,
                            "pool": false,
                            "pool_table": false,
                            "pots_and_pans": false,
                            "private_entrance": false,
                            "product_launch": false,
                            "refrigerator": false,
                            "road_biking": false,
                            "rock_climbing": false,
                            "rollerblading": false,
                            "room_darkening_shades": false,
                            "running": false,
                            "sailing": false,
                            "sandy_beach": false,
                            "sauna": false,
                            "scuba_diving": false,
                            "shampoo_soap": false,
                            "single_level_home": false,
                            "skating": false,
                            "ski_in_ski_out": false,
                            "skydiving": false,
                            "snorkeling": false,
                            "snowboarding": false,
                            "snowmobile_trail": false,
                            "snowshoeing": false,
                            "spa_services": false,
                            "sport_team_training": false,
                            "stair_gates": false,
                            "stove": false,
                            "swimming": false,
                            "table_corner_guards": false,
                            "tea_coffee_included": false,
                            "tennis": false,
                            "toilet_paper": false,
                            "towels": false,
                            "tree_climbing": false,
                            "tv": false,
                            "volleyball": false,
                            "volleyball_net": false,
                            "washer": false,
                            "water_skiing": false,
                            "water_sliding": false,
                            "wedding": false,
                            "wheelchair_accessible": false,
                            "whitewater_rafting": false,
                            "window_guards": false,
                            "windsurfing": false,
                            "wireless_internet": true
        }


+ Response 200 (application/json)

    
    + Body

            {
              "data": {
                       "access_to_water": true,
                        "air_conditioning": true,
                        "pets_are_welcome": false,
                        "alpine_skiing": false,
                        "art_show": false,
                        "atv_trail": false,
                        "baby_bath": false,
                        "baby_monitor": false,
                        "babysitter_referrals": false,
                        "bachelorette_party": false,
                        "basketball": false,
                        "bbq_grill": false,
                        "beach_chairs": false,
                        "beachfront": false,
                        "bed_linens": false,
                        "birthday_party": false,
                        "boating": false,
                        "breakfast_included": false,
                        "by_a_river": false,
                        "cable_tv": false,
                        "canoeing": false,
                        "changing_tablebathtub": false,
                        "caving": false,
                        "cooking_basics": false,
                        "corporate_meeting": false,
                        "conference": false,
                        "coffee_maker": false,
                        "childrens_dinnerware": false,
                        "childrens_books_and_toys": false,
                        "crib": false,
                        "cross_country_skiing": false,
                        "deepsea_fishing": false,
                        "dishes_and_silverware": false,
                        "dishwasher": false,
                        "dock": false,
                        "dryer": false,
                        "dvd_blue_ray": false,
                        "ev_charger": false,
                        "executive_retreat": false,
                        "extra_pillows_and_blankets": false,
                        "fire_pit": false,
                        "fireplace_guards": false,
                        "firewood_included": false,
                        "free_gym_fitness_centre": false,
                        "free_parking_on_premises": false,
                        "friends_family_meeting": false,
                        "game_console": false,
                        "garden_or_backyard": false,
                        "golf": false,
                        "guided_tours": false,
                        "hair_dryer": false,
                        "hamak": false,
                        "hangers_in_closets": false,
                        "heated_floors": false,
                        "heating": false,
                        "high_chair": false,
                        "hiking": false,
                        "hockey": false,
                        "home_essentials": false,
                        "horseback_riding": false,
                        "foosball_table": false,
                        "fishing": false,
                        "hot_tub_spa": false,
                        "hot_water": false,
                        "ice_climbing": false,
                        "indoor_fireplace": false,
                        "iron": false,
                        "jet_skiing": false,
                        "kayaking": false,
                        "kitchen": false,
                        "lakefront": false,
                        "laptop_friendly_workspace": false,
                        "life_jackets": false,
                        "maid_service_included": false,
                        "microwave": false,
                        "mountain_biking": false,
                        "outlet_covers": false,
                        "oven": false,
                        "pack_n_playtravel_crib": false,
                        "parasailing": false,
                        "patio_furniture": false,
                        "patio_or_balcony": false,
                        "photo_film_shoot": false,
                        "ping_pong_table": false,
                        "pool": false,
                        "pool_table": false,
                        "pots_and_pans": false,
                        "private_entrance": false,
                        "product_launch": false,
                        "refrigerator": false,
                        "road_biking": false,
                        "rock_climbing": false,
                        "rollerblading": false,
                        "room_darkening_shades": false,
                        "running": false,
                        "sailing": false,
                        "sandy_beach": false,
                        "sauna": false,
                        "scuba_diving": false,
                        "shampoo_soap": false,
                        "single_level_home": false,
                        "skating": false,
                        "ski_in_ski_out": false,
                        "skydiving": false,
                        "snorkeling": false,
                        "snowboarding": false,
                        "snowmobile_trail": false,
                        "snowshoeing": false,
                        "spa_services": false,
                        "sport_team_training": false,
                        "stair_gates": false,
                        "stove": false,
                        "swimming": false,
                        "table_corner_guards": false,
                        "tea_coffee_included": false,
                        "tennis": false,
                        "toilet_paper": false,
                        "towels": false,
                        "tree_climbing": false,
                        "tv": false,
                        "volleyball": false,
                        "volleyball_net": false,
                        "washer": false,
                        "water_skiing": false,
                        "water_sliding": false,
                        "wedding": false,
                        "wheelchair_accessible": false,
                        "whitewater_rafting": false,
                        "window_guards": false,
                        "windsurfing": false,
                        "wireless_internet": true
                        }
            }
            

+ Response 400 (application/json)

    + Body

             {
                  "message": "Unauthenticated."
             }
                

+ Response 404 (application/json)

    + Body

             {
                    "errors": "Resource not found!"
             }


+ Response 422 (application/json)

    + Body

             {
                  "message": "The given data was invalid.",
                  "errors": {
                    "amenities": [
                      "The amenities field is required."
                    ],
                    "amenities.access_to_water": [
                      "The amenities.access to water field is required."
                    ],
                    "amenities.air_conditioning": [
                      "The amenities.air conditioning field is required."
                    ],
                    "amenities.pets_are_welcome": [
                      "The amenities.pets are welcome field is required."
                    ],
                    "amenities.alpine_skiing": [
                      "The amenities.alpine skiing field is required."
                    ],
                    "amenities.art_show": [
                      "The amenities.art show field is required."
                    ],
                    "amenities.atv_trail": [
                      "The amenities.atv trail field is required."
                    ],
                    "amenities.baby_bath": [
                      "The amenities.baby bath field is required."
                    ],
                    "amenities.baby_monitor": [
                      "The amenities.baby monitor field is required."
                    ],
                    "amenities.babysitter_referrals": [
                      "The amenities.babysitter referrals field is required."
                    ],
                    "amenities.bachelorette_party": [
                      "The amenities.bachelorette party field is required."
                    ],
                    "amenities.basketball": [
                      "The amenities.basketball field is required."
                    ],
                    "amenities.bbq_grill": [
                      "The amenities.bbq grill field is required."
                    ],
                    "amenities.beach_chairs": [
                      "The amenities.beach chairs field is required."
                    ],
                    "amenities.beachfront": [
                      "The amenities.beachfront field is required."
                    ],
                    "amenities.bed_linens": [
                      "The amenities.bed linens field is required."
                    ],
                    "amenities.birthday_party": [
                      "The amenities.birthday party field is required."
                    ],
                    "amenities.boating": [
                      "The amenities.boating field is required."
                    ],
                    "amenities.breakfast_included": [
                      "The amenities.breakfast included field is required."
                    ],
                    "amenities.by_a_river": [
                      "The amenities.by a river field is required."
                    ],
                    "amenities.cable_tv": [
                      "The amenities.cable tv field is required."
                    ],
                    "amenities.canoeing": [
                      "The amenities.canoeing field is required."
                    ],
                    "amenities.changing_tablebathtub": [
                      "The amenities.changing tablebathtub field is required."
                    ],
                    "amenities.caving": [
                      "The amenities.caving field is required."
                    ],
                    "amenities.cooking_basics": [
                      "The amenities.cooking basics field is required."
                    ],
                    "amenities.corporate_meeting": [
                      "The amenities.corporate meeting field is required."
                    ],
                    "amenities.conference": [
                      "The amenities.conference field is required."
                    ],
                    "amenities.coffee_maker": [
                      "The amenities.coffee maker field is required."
                    ],
                    "amenities.childrens_dinnerware": [
                      "The amenities.childrens dinnerware field is required."
                    ],
                    "amenities.childrens_books_and_toys": [
                      "The amenities.childrens books and toys field is required."
                    ],
                    "amenities.crib": [
                      "The amenities.crib field is required."
                    ],
                    "amenities.cross_country_skiing": [
                      "The amenities.cross country skiing field is required."
                    ],
                    "amenities.deepsea_fishing": [
                      "The amenities.deepsea fishing field is required."
                    ],
                    "amenities.dishes_and_silverware": [
                      "The amenities.dishes and silverware field is required."
                    ],
                    "amenities.dishwasher": [
                      "The amenities.dishwasher field is required."
                    ],
                    "amenities.dock": [
                      "The amenities.dock field is required."
                    ],
                    "amenities.dryer": [
                      "The amenities.dryer field is required."
                    ],
                    "amenities.dvd_blue_ray": [
                      "The amenities.dvd blue ray field is required."
                    ],
                    "amenities.ev_charger": [
                      "The amenities.ev charger field is required."
                    ],
                    "amenities.executive_retreat": [
                      "The amenities.executive retreat field is required."
                    ],
                    "amenities.extra_pillows_and_blankets": [
                      "The amenities.extra pillows and blankets field is required."
                    ],
                    "amenities.fire_pit": [
                      "The amenities.fire pit field is required."
                    ],
                    "amenities.fireplace_guards": [
                      "The amenities.fireplace guards field is required."
                    ],
                    "amenities.firewood_included": [
                      "The amenities.firewood included field is required."
                    ],
                    "amenities.free_gym_fitness_centre": [
                      "The amenities.free gym fitness centre field is required."
                    ],
                    "amenities.free_parking_on_premises": [
                      "The amenities.free parking on premises field is required."
                    ],
                    "amenities.friends_family_meeting": [
                      "The amenities.friends family meeting field is required."
                    ],
                    "amenities.game_console": [
                      "The amenities.game console field is required."
                    ],
                    "amenities.garden_or_backyard": [
                      "The amenities.garden or backyard field is required."
                    ],
                    "amenities.golf": [
                      "The amenities.golf field is required."
                    ],
                    "amenities.guided_tours": [
                      "The amenities.guided tours field is required."
                    ],
                    "amenities.hair_dryer": [
                      "The amenities.hair dryer field is required."
                    ],
                    "amenities.hamak": [
                      "The amenities.hamak field is required."
                    ],
                    "amenities.hangers_in_closets": [
                      "The amenities.hangers in closets field is required."
                    ],
                    "amenities.heated_floors": [
                      "The amenities.heated floors field is required."
                    ],
                    "amenities.heating": [
                      "The amenities.heating field is required."
                    ],
                    "amenities.high_chair": [
                      "The amenities.high chair field is required."
                    ],
                    "amenities.hiking": [
                      "The amenities.hiking field is required."
                    ],
                    "amenities.hockey": [
                      "The amenities.hockey field is required."
                    ],
                    "amenities.home_essentials": [
                      "The amenities.home essentials field is required."
                    ],
                    "amenities.horseback_riding": [
                      "The amenities.horseback riding field is required."
                    ],
                    "amenities.foosball_table": [
                      "The amenities.foosball table field is required."
                    ],
                    "amenities.fishing": [
                      "The amenities.fishing field is required."
                    ],
                    "amenities.hot_tub_spa": [
                      "The amenities.hot tub spa field is required."
                    ],
                    "amenities.hot_water": [
                      "The amenities.hot water field is required."
                    ],
                    "amenities.ice_climbing": [
                      "The amenities.ice climbing field is required."
                    ],
                    "amenities.indoor_fireplace": [
                      "The amenities.indoor fireplace field is required."
                    ],
                    "amenities.iron": [
                      "The amenities.iron field is required."
                    ],
                    "amenities.jet_skiing": [
                      "The amenities.jet skiing field is required."
                    ],
                    "amenities.kayaking": [
                      "The amenities.kayaking field is required."
                    ],
                    "amenities.kitchen": [
                      "The amenities.kitchen field is required."
                    ],
                    "amenities.lakefront": [
                      "The amenities.lakefront field is required."
                    ],
                    "amenities.laptop_friendly_workspace": [
                      "The amenities.laptop friendly workspace field is required."
                    ],
                    "amenities.life_jackets": [
                      "The amenities.life jackets field is required."
                    ],
                    "amenities.maid_service_included": [
                      "The amenities.maid service included field is required."
                    ],
                    "amenities.microwave": [
                      "The amenities.microwave field is required."
                    ],
                    "amenities.mountain_biking": [
                      "The amenities.mountain biking field is required."
                    ],
                    "amenities.outlet_covers": [
                      "The amenities.outlet covers field is required."
                    ],
                    "amenities.oven": [
                      "The amenities.oven field is required."
                    ],
                    "amenities.pack_n_playtravel_crib": [
                      "The amenities.pack n playtravel crib field is required."
                    ],
                    "amenities.parasailing": [
                      "The amenities.parasailing field is required."
                    ],
                    "amenities.patio_furniture": [
                      "The amenities.patio furniture field is required."
                    ],
                    "amenities.patio_or_balcony": [
                      "The amenities.patio or balcony field is required."
                    ],
                    "amenities.photo_film_shoot": [
                      "The amenities.photo film shoot field is required."
                    ],
                    "amenities.ping_pong_table": [
                      "The amenities.ping pong table field is required."
                    ],
                    "amenities.pool": [
                      "The amenities.pool field is required."
                    ],
                    "amenities.pool_table": [
                      "The amenities.pool table field is required."
                    ],
                    "amenities.pots_and_pans": [
                      "The amenities.pots and pans field is required."
                    ],
                    "amenities.private_entrance": [
                      "The amenities.private entrance field is required."
                    ],
                    "amenities.product_launch": [
                      "The amenities.product launch field is required."
                    ],
                    "amenities.refrigerator": [
                      "The amenities.refrigerator field is required."
                    ],
                    "amenities.road_biking": [
                      "The amenities.road biking field is required."
                    ],
                    "amenities.rock_climbing": [
                      "The amenities.rock climbing field is required."
                    ],
                    "amenities.rollerblading": [
                      "The amenities.rollerblading field is required."
                    ],
                    "amenities.room_darkening_shades": [
                      "The amenities.room darkening shades field is required."
                    ],
                    "amenities.running": [
                      "The amenities.running field is required."
                    ],
                    "amenities.sailing": [
                      "The amenities.sailing field is required."
                    ],
                    "amenities.sandy_beach": [
                      "The amenities.sandy beach field is required."
                    ],
                    "amenities.sauna": [
                      "The amenities.sauna field is required."
                    ],
                    "amenities.scuba_diving": [
                      "The amenities.scuba diving field is required."
                    ],
                    "amenities.shampoo_soap": [
                      "The amenities.shampoo soap field is required."
                    ],
                    "amenities.single_level_home": [
                      "The amenities.single level home field is required."
                    ],
                    "amenities.skating": [
                      "The amenities.skating field is required."
                    ],
                    "amenities.ski_in_ski_out": [
                      "The amenities.ski in ski out field is required."
                    ],
                    "amenities.skydiving": [
                      "The amenities.skydiving field is required."
                    ],
                    "amenities.snorkeling": [
                      "The amenities.snorkeling field is required."
                    ],
                    "amenities.snowboarding": [
                      "The amenities.snowboarding field is required."
                    ],
                    "amenities.snowmobile_trail": [
                      "The amenities.snowmobile trail field is required."
                    ],
                    "amenities.snowshoeing": [
                      "The amenities.snowshoeing field is required."
                    ],
                    "amenities.spa_services": [
                      "The amenities.spa services field is required."
                    ],
                    "amenities.sport_team_training": [
                      "The amenities.sport team training field is required."
                    ],
                    "amenities.stair_gates": [
                      "The amenities.stair gates field is required."
                    ],
                    "amenities.stove": [
                      "The amenities.stove field is required."
                    ],
                    "amenities.swimming": [
                      "The amenities.swimming field is required."
                    ],
                    "amenities.table_corner_guards": [
                      "The amenities.table corner guards field is required."
                    ],
                    "amenities.tea_coffee_included": [
                      "The amenities.tea coffee included field is required."
                    ],
                    "amenities.tennis": [
                      "The amenities.tennis field is required."
                    ],
                    "amenities.toilet_paper": [
                      "The amenities.toilet paper field is required."
                    ],
                    "amenities.towels": [
                      "The amenities.towels field is required."
                    ],
                    "amenities.tree_climbing": [
                      "The amenities.tree climbing field is required."
                    ],
                    "amenities.tv": [
                      "The amenities.tv field is required."
                    ],
                    "amenities.volleyball": [
                      "The amenities.volleyball field is required."
                    ],
                    "amenities.volleyball_net": [
                      "The amenities.volleyball net field is required."
                    ],
                    "amenities.washer": [
                      "The amenities.washer field is required."
                    ],
                    "amenities.water_skiing": [
                      "The amenities.water skiing field is required."
                    ],
                    "amenities.water_sliding": [
                      "The amenities.water sliding field is required."
                    ],
                    "amenities.wedding": [
                      "The amenities.wedding field is required."
                    ],
                    "amenities.wheelchair_accessible": [
                      "The amenities.wheelchair accessible field is required."
                    ],
                    "amenities.whitewater_rafting": [
                      "The amenities.whitewater rafting field is required."
                    ],
                    "amenities.window_guards": [
                      "The amenities.window guards field is required."
                    ],
                    "amenities.windsurfing": [
                      "The amenities.windsurfing field is required."
                    ],
                    "amenities.wireless_internet": [
                      "The amenities.wireless internet field is required."
                    ]
                  }
                }

## property special prices [/api/properties/{uuid}/special-prices/]
+ Parameters

    + uuid (required, string) ... ID of the Property


### api/properties/{uuid}/spacial-prices [GET]
+ Request (application/json)

        {
            "api_token": ""
        }


+ Response 200 (application/json)

    
    + Body

            {
              
                       "data": [
                                    {
                                      "id": "e530785b-9c51-4da4-9617-2ad62c484aa3",
                                      "Price": 5,
                                      "date": "2018-11-29T00:00:00.000000Z"
                                    },
                                    {
                                      "id": "9ba1cb1a-393a-44e8-bd4d-e368f39c7bf9",
                                      "Price": 5,
                                      "date": "2018-12-25T00:00:00.000000Z"
                                    },
                                    {
                                      "id": "abb2955b-d633-4b6a-814f-56c51faf4604",
                                      "Price": 5,
                                      "date": "2018-12-26T00:00:00.000000Z"
                                    },
                                    {
                                      "id": "a50b24ce-c062-47e0-8c08-ee6d3c6088b1",
                                      "Price": 5,
                                      "date": "2018-12-27T00:00:00.000000Z"
                                    }
                      ]
            }
            

+ Response 400 (application/json)

    + Body

             {
                  "message": "Unauthenticated."
             }
                

+ Response 404 (application/json)

    + Body

             {
                    "errors": "Resource not found!"
             }
### api/properties/{uuid}/spacial-prices [PUT]
+ Request (application/json)

        {
            "api_token": "",
            "start_date" : "2019-04-20",
            "end_date" : "2019-04-30",
            "price" : 421
        }


+ Response 200 (application/json)

    
    + Body

            {
              
                       "data": [
                                    {
                                      "id": "e530785b-9c51-4da4-9617-2ad62c484aa3",
                                      "Price": 5,
                                      "date": "2018-11-29 T00:00:00.000000Z"
                                    },
                                    {
                                      "id": "9ba1cb1a-393a-44e8-bd4d-e368f39c7bf9",
                                      "Price": 5,
                                      "date": "2018-12-25 T00:00:00.000000Z"
                                    },
                                    {
                                      "id": "abb2955b-d633-4b6a-814f-56c51faf4604",
                                      "Price": 5,
                                      "date": "2018-12-26 T00:00:00.000000Z"
                                    },
                                    {
                                      "id": "a50b24ce-c062-47e0-8c08-ee6d3c6088b1",
                                      "Price": 5,
                                      "date": "2018-12-27 T00:00:00.000000Z"
                                    }
                      ]
            }
            

+ Response 400 (application/json)

    + Body

             {
                  "message": "Unauthenticated."
             }
                

+ Response 404 (application/json)

    + Body

             {
                    "errors": "Resource not found!"
             }
### api/properties/{uuid}/spacial-prices [DELETE]
+ Request (application/json)

        {
            "api_token": "",
            "start_date" : "2019-04-20",
            "end_date" : "2019-04-30",
            "price" : 421
        }


+ Response 200 (application/json)

    
    + Body

            {
              
                 "data": []
            }
            

+ Response 400 (application/json)

    + Body

             {
                  "message": "Unauthenticated."
             }
                

+ Response 404 (application/json)

    + Body

             {
                    "errors": "Resource not found!"
             }


## property blocked-dates [/api/properties/{uuid}/blocked-dates] 
+ Parameters

    + uuid (required, string) ... ID of the Property

### api/properties/{uuid}/blocked-dates [GET]

+ Request (application/json)

        {
            "api_token": ""
        }

+ Response 200 (application/json)

    
    + Body

            {
                  "data": [
                    {
                      "id": "9ff9952b-0c24-4fd0-a538-44474a75e128",
                      "date": "2019-01-03T00:00:00.000000Z",
                      "note": "for cleaning"
                    },
                    {
                      "id": "83df06f2-3056-4fd5-a484-379d424af4cb",
                      "date": "2019-01-04T00:00:00.000000Z",
                      "note": "for cleaning"
                    },
                    {
                      "id": "7cfca579-b1ce-40e7-b467-8b8f1ed96d61",
                      "date": "2019-01-05T00:00:00.000000Z",
                      "note": "for cleaning"
                    },
                    {
                      "id": "1f2c5775-ca6d-4baf-913c-37b33921fa52",
                      "date": "2018-12-30T00:00:00.000000Z",
                      "note": "for cleaning"
                    },
                    {
                      "id": "50a947c6-7081-465f-8de8-97b4a20b0879",
                      "date": "2019-01-24T00:00:00.000000Z",
                      "note": "for cleaning"
                    }
                  ]
                }

            

+ Response 400 (application/json)

    + Body

             {
                  "message": "Unauthenticated."
             }
                

+ Response 404 (application/json)

    + Body

             {
                    "errors": "Resource not found!"
             }
            
### api/properties/{uuid}/blocked-dates [POST]


+ Request (application/json)

        {
            "api_token": "",
            "start_date" : "2019-01-3",
            "end_date" : "2019-01-05",
            "note" : "for cleaning",
        }

+ Response 200 (application/json)

    
    + Body

            {
                  "data": [
                    {
                      "id": "9ff9952b-0c24-4fd0-a538-44474a75e128",
                      "date": "2019-01-03T00:00:00.000000Z",
                      "note": "for cleaning"
                    },
                    {
                      "id": "83df06f2-3056-4fd5-a484-379d424af4cb",
                      "date": "2019-01-04T00:00:00.000000Z",
                      "note": "for cleaning"
                    },
                    {
                      "id": "7cfca579-b1ce-40e7-b467-8b8f1ed96d61",
                      "date": "2019-01-05T00:00:00.000000Z",
                      "note": "for cleaning"
                    },
                    {
                      "id": "1f2c5775-ca6d-4baf-913c-37b33921fa52",
                      "date": "2018-12-30T00:00:00.000000Z",
                      "note": "for cleaning"
                    },
                    {
                      "id": "50a947c6-7081-465f-8de8-97b4a20b0879",
                      "date": "2019-01-24T00:00:00.000000Z",
                      "note": "for cleaning"
                    }
                  ]
                }

            

+ Response 400 (application/json)

    + Body

             {
                  "message": "Unauthenticated."
             }
                

+ Response 404 (application/json)

    + Body

             {
                    "errors": "Resource not found!"
             }
             
### api/properties/{uuid}/blocked-dates [DELETE]


+ Request (application/json)

        {
            "api_token": "",
            "start_date" : "2019-01-3",
            "end_date" : "2019-01-05",
        }

+ Response 200 (application/json)

    
    + Body

            {
                  "data": [
                   
                    {
                      "id": "1f2c5775-ca6d-4baf-913c-37b33921fa52",
                      "date": "2018-12-30T00:00:00.000000Z",
                      "note": "for cleaning"
                    },
                    {
                      "id": "50a947c6-7081-465f-8de8-97b4a20b0879",
                      "date": "2019-01-24T00:00:00.000000Z",
                      "note": "for cleaning"
                    }
                  ]
                }

            

+ Response 400 (application/json)

    + Body

             {
                  "message": "Unauthenticated."
             }
                

+ Response 404 (application/json)

    + Body

             {
                    "errors": "Resource not found!"
             }
             
             
             
             
## property descriptions [/api/properties/{uuid}/descriptions] 
+ Parameters

    + uuid (required, string) ... ID of the Property

### api/properties/{uuid}/descriptions [GET]

+ Request (application/json)

        {
            "api_token": ""
        }

+ Response 200 (application/json)

    
    + Body

            {
              "data":[
                    {
                      "id": "367298fc-9495-45fc-aa1a-8c35663bd4f7",
                      "language": "english",
                      "title": "nagpur test property",
                      "about_this_property": "lora lpsm doller content sit amit.",
                      "home_access": "lora lpsm doller content sit amit.",
                      "host_availibility": "lora lpsm doller content sit amit.",
                      "other_things_to_know": "lora lpsm doller content sit amit.",
                      "birds_eye_view": "lora lpsm doller content sit amit.",
                      "travelling_around": "lora lpsm doller content sit amit.",
                      "description": "lora lpsm doller content sit amit."
                    },
                    {
                      "id": "1e1a7c36-ddc6-44e9-b7da-85a1240c42e5",
                      "language": "frensh",
                      "title": "nagpur test property",
                      "about_this_property": "lora lpsm doller content sit amit.",
                      "home_access": "lora lpsm doller content sit amit.",
                      "host_availibility": "lora lpsm doller content sit amit.",
                      "other_things_to_know": "lora lpsm doller content sit amit.",
                      "birds_eye_view": "lora lpsm doller content sit amit.",
                      "travelling_around": "lora lpsm doller content sit amit.",
                      "description": "lora lpsm doller content sit amit."
                    }
                  ]
            }

            

+ Response 400 (application/json)

    + Body

             {
                  "message": "Unauthenticated."
             }
                

+ Response 404 (application/json)

    + Body

             {
                    "errors": "Resource not found!"
             }
             

### api/properties/{uuid}/descriptions [PUT]

+ Request (application/json)

        {
            "api_token": "",
            "language": "english",
            "title": "nagpur test property",
            "about_this_property": "lora lpsm doller content sit amit.",
            "home_access": "lora lpsm doller content sit amit.",
            "host_availibility": "lora lpsm doller content sit amit.",
            "other_things_to_know": "lora lpsm doller content sit amit.",
            "birds_eye_view": "lora lpsm doller content sit amit.",
            "travelling_around": "lora lpsm doller content sit amit.",
            "description": "lora lpsm doller content sit amit."
        }

+ Response 200 (application/json)

    
    + Body

            {
              "data":[
                    {
                      "id": "367298fc-9495-45fc-aa1a-8c35663bd4f7",
                      "language": "english",
                      "title": "nagpur test property",
                      "about_this_property": "lora lpsm doller content sit amit.",
                      "home_access": "lora lpsm doller content sit amit.",
                      "host_availibility": "lora lpsm doller content sit amit.",
                      "other_things_to_know": "lora lpsm doller content sit amit.",
                      "birds_eye_view": "lora lpsm doller content sit amit.",
                      "travelling_around": "lora lpsm doller content sit amit.",
                      "description": "lora lpsm doller content sit amit."
                    }
                  ]
            }

            

+ Response 400 (application/json)

    + Body

             {
                  "message": "Unauthenticated."
             }
                

+ Response 404 (application/json)

    + Body

             {
                    "errors": "Resource not found!"
             }
             
### api/properties/{uuid}/descriptions [DELETE]

+ Request (application/json)

        {
            "api_token": "",
            "description_id": "367298fc-9495-45fc-aa1a-8c35663bd4f7",
        }

+ Response 200 (application/json)

    
    + Body

            {
              "data":[
                    {
                      "id": "367298fc-9495-45fc-aa1a-8c35663bd4f7",
                      "language": "english",
                      "title": "nagpur test property",
                      "about_this_property": "lora lpsm doller content sit amit.",
                      "home_access": "lora lpsm doller content sit amit.",
                      "host_availibility": "lora lpsm doller content sit amit.",
                      "other_things_to_know": "lora lpsm doller content sit amit.",
                      "birds_eye_view": "lora lpsm doller content sit amit.",
                      "travelling_around": "lora lpsm doller content sit amit.",
                      "description": "lora lpsm doller content sit amit."
                    }
                  ]
            }

            

+ Response 400 (application/json)

    + Body

             {
                  "message": "Unauthenticated."
             }
                

+ Response 404 (application/json)

    + Body

             {
                    "errors": "Resource not found!"
             }